@echo off
echo Инициализация Git репозитория...
git init
echo Добавление удаленного репозитория...
git remote add origin https://github.com/Volxonka/telegram-bot-umc.git
echo Добавление всех файлов...
git add .
echo Коммит изменений...
git commit -m "Initial commit: Telegram bot for UMC"
echo Отправка в GitHub...
git push -u origin main
echo Готово! Репозиторий обновлен.
pause
